Update master to bigloo4.2a-beta09Sep15

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,10 +1,10 @@
-#!/bin/sh
+!/bin/sh
 #*=====================================================================*/
 #*    serrano/prgm/project/bigloo/configure                            */
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Sat Jun  6 11:08:40 2015 (serrano)                */
+#*    Last change :  Fri Sep  4 12:32:53 2015 (serrano)                */
 #*    Copyright   :  1994-2015 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -39,7 +39,8 @@ tmpdir=/tmp
 lispdir=
 
 #*--- api -------------------------------------------------------------*/
-apis="pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib gstreamer text srfi1 srfi27 packrat crypto openpgp phone alsa mpg123 flac wav avahi phidget csv upnp libuv"
+importantapis="pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib text srfi1 srfi27 packrat crypto openpgp csv upnp libuv"
+apis="$importantapis gstreamer phidget alsa wav flac mpg123 phone avahi"
 
 #*--- bee configuration -----------------------------------------------*/
 bee=partial # "partial" or "full"
@@ -311,6 +312,7 @@ droidtmp=
 #*---------------------------------------------------------------------*/
 #*--- configure debugging ---------------------------------------------*/
 configurelog=configure.log
+abortmissing=no
 
 #*--- The basename of the compiler and tools --------------------------*/
 afile=bglafile
@@ -472,6 +474,9 @@ while : ; do
 
     --configure.log=*)
       configurelog="`echo $1 | sed 's/^[^=]*=//'`";;
+
+    --abort-missing)
+      abortmissing=yes;;
 
     --bindir=*)
       bindir="`echo $1 | sed 's/^[^=]*=//'`";;
@@ -1071,6 +1076,7 @@ while : ; do
       echo "   --bigloo_config.jvm[=file]" >&2;
       echo "   --Makefile.config=file" >&2;
       echo "   --$configurelog=file" >&2;
+      echo "   --abort-missing (abort as soon as a system lib is missing)" >&2;
       echo "   --no-summary" >&2;
       echo "   --bootconfig" >&2;
       echo "   --bootdir=dir" >&2;
@@ -4035,6 +4041,54 @@ cat $deb.in \
 chmod a+rx $deb
 
 #*---------------------------------------------------------------------*/
+#*    Checking missing dependencies                                    */
+#*---------------------------------------------------------------------*/
+if [ "$abortmissing " = "yes " ]; then
+    missing="";
+    
+    for p in $importantapis; do
+       res=0;
+       for q in $apis; do
+           if [ $q = $p ]; then
+	       res=1;
+	       break;
+	   fi
+       done
+       if [ $res = "0" ]; then
+	   missing="$p $missing"
+       fi
+    done
+
+    if [ "$missing " != " " ]; then
+	echo ""
+	echo "*** ERROR Missing libraries: $missing" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+
+    if [ "$unistring " = "no " ]; then
+	echo ""
+	echo "*** ERROR Missing library: unistring" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+    
+    if [ ! "$regexp " = "pcre " ]; then
+	echo ""
+	echo "*** ERROR Missing library: pcre" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+    
+    if [ ! "$havegmp= " = "1 " ]; then
+	echo ""
+	echo "*** ERROR Missing library: gmp" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+fi
+
+#*---------------------------------------------------------------------*/
 #*    Ok, we are done now                                              */
 #*---------------------------------------------------------------------*/
 bcke="native:yes"
@@ -4043,6 +4097,7 @@ if [ "$jvmbackend" = "yes" -o "$jvmbackend" = "force" ]; then
 else
   bcke="$bcke JVM:no"
 fi
+
 echo  >> $configurelog
 echo  >> $configurelog
 echo "** Configuration summary **" >> $configurelog
